name: notebook
channels:
  - conda-forge
dependencies:
  - ipywidgets=8
  - jupyterlab=4
  - jupyterlab-language-pack-fr-FR
  - matplotlib
  - numpy
  - nodejs=20
  - python >=3.10,<3.11
  - xeus-python
